#pragma once

#ifndef VERSION_HPP
#define VERSION_HPP

#define LINUX_IMAGE_BACKUP_TOOL_MAJOR_VERSION 0
#define LINUX_IMAGE_BACKUP_TOOL_MINOR_VERSION 0
#define LINUX_IMAGE_BACKUP_TOOL_PATCH_VERSION 1
#define LINUX_IMAGE_BACKUP_TOOL_BUILD_NUMBER 1
#define LINUX_IMAGE_BACKUP_TOOL_BUILD_TYPE "alpha"
#define LINUX_IMAGE_BACKUP_TOOL_BUILD_TYPE_NUMBER 0

#endif // !VERSION_HPP